### ISSUE TITLE
Twisted support

### ISSUE THREAD

**Issue by corydodt** [shaunduncan/smokesignal#13]
There are many instances where it is useful to synchronize the results of a signal. Also, current smokesignal has no support for handling errors (it simply eats them).

Enhance smokesignal by providing the ability for emit() to return a deferred which fires with the results of all the callbacks. Further support error handling by adding standard errback support.

PR forthcoming.

**Comment by corydodt** [comment]
https://github.com/shaunduncan/smokesignal/pull/14/files PR

**Comment by shaunduncan** [comment]
I reviewed and merged the PR that adds Twisted support. I am going to mark this issue as closed. Please reopen the issue if you feel it was closed in error.

Thanks!

**Comment by corydodt** [comment]
Glad I could improve the project! :)
